// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passsquale/product_item_api/v1/product_item_api.proto

package product_item_api

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MaybeTimestamp struct {
	Time                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MaybeTimestamp) Reset()         { *m = MaybeTimestamp{} }
func (m *MaybeTimestamp) String() string { return proto.CompactTextString(m) }
func (*MaybeTimestamp) ProtoMessage()    {}
func (*MaybeTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3729b5f197a34503, []int{0}
}

func (m *MaybeTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaybeTimestamp.Unmarshal(m, b)
}
func (m *MaybeTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaybeTimestamp.Marshal(b, m, deterministic)
}
func (m *MaybeTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaybeTimestamp.Merge(m, src)
}
func (m *MaybeTimestamp) XXX_Size() int {
	return xxx_messageInfo_MaybeTimestamp.Size(m)
}
func (m *MaybeTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_MaybeTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_MaybeTimestamp proto.InternalMessageInfo

func (m *MaybeTimestamp) GetTime() *timestamppb.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Item struct {
	ID                   uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerID              uint64                 `protobuf:"varint,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	ProductID            uint64                 `protobuf:"varint,3,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Title                string                 `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Created              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              *MaybeTimestamp        `protobuf:"bytes,6,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3729b5f197a34503, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetOwnerID() uint64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *Item) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetCreated() *timestamppb.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item) GetUpdated() *MaybeTimestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type DescribeItemV1Request struct {
	ItemID               uint64   `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeItemV1Request) Reset()         { *m = DescribeItemV1Request{} }
func (m *DescribeItemV1Request) String() string { return proto.CompactTextString(m) }
func (*DescribeItemV1Request) ProtoMessage()    {}
func (*DescribeItemV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3729b5f197a34503, []int{2}
}

func (m *DescribeItemV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeItemV1Request.Unmarshal(m, b)
}
func (m *DescribeItemV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeItemV1Request.Marshal(b, m, deterministic)
}
func (m *DescribeItemV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeItemV1Request.Merge(m, src)
}
func (m *DescribeItemV1Request) XXX_Size() int {
	return xxx_messageInfo_DescribeItemV1Request.Size(m)
}
func (m *DescribeItemV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeItemV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeItemV1Request proto.InternalMessageInfo

func (m *DescribeItemV1Request) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type DescribeItemV1Response struct {
	Value                *Item    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeItemV1Response) Reset()         { *m = DescribeItemV1Response{} }
func (m *DescribeItemV1Response) String() string { return proto.CompactTextString(m) }
func (*DescribeItemV1Response) ProtoMessage()    {}
func (*DescribeItemV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3729b5f197a34503, []int{3}
}

func (m *DescribeItemV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeItemV1Response.Unmarshal(m, b)
}
func (m *DescribeItemV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeItemV1Response.Marshal(b, m, deterministic)
}
func (m *DescribeItemV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeItemV1Response.Merge(m, src)
}
func (m *DescribeItemV1Response) XXX_Size() int {
	return xxx_messageInfo_DescribeItemV1Response.Size(m)
}
func (m *DescribeItemV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeItemV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeItemV1Response proto.InternalMessageInfo

func (m *DescribeItemV1Response) GetValue() *Item {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*MaybeTimestamp)(nil), "passsquale.product_item_api.v1.MaybeTimestamp")
	proto.RegisterType((*Item)(nil), "passsquale.product_item_api.v1.Item")
	proto.RegisterType((*DescribeItemV1Request)(nil), "passsquale.product_item_api.v1.DescribeItemV1Request")
	proto.RegisterType((*DescribeItemV1Response)(nil), "passsquale.product_item_api.v1.DescribeItemV1Response")
}

func init() {
	proto.RegisterFile("passsquale/product_item_api/v1/product_item_api.proto", fileDescriptor_3729b5f197a34503)
}

var fileDescriptor_3729b5f197a34503 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0xb1, 0x71, 0x12, 0xf5, 0x21, 0x75, 0x31, 0x6a, 0xc1, 0xb2, 0x2a, 0x1a, 0x59, 0x2c,
	0xba, 0xa0, 0x63, 0x25, 0x50, 0x84, 0x60, 0x03, 0xc1, 0x0b, 0xbc, 0x40, 0x20, 0x13, 0xba, 0x60,
	0x53, 0x4d, 0xe2, 0x47, 0x35, 0x92, 0xff, 0x4c, 0x3d, 0x63, 0x23, 0x84, 0xd8, 0x70, 0x05, 0x0e,
	0xc0, 0x39, 0x38, 0x07, 0x57, 0xe8, 0x29, 0x58, 0xa1, 0x99, 0xc9, 0x50, 0x91, 0x20, 0xa2, 0xee,
	0xfc, 0xbe, 0xf7, 0xfd, 0xde, 0xcc, 0xfb, 0x6c, 0xc3, 0x89, 0x60, 0x52, 0xca, 0x8b, 0x8e, 0x95,
	0x98, 0x88, 0xb6, 0x29, 0xba, 0xa5, 0x3a, 0xe3, 0x0a, 0xab, 0x33, 0x26, 0x78, 0xd2, 0x4f, 0x36,
	0x34, 0x2a, 0xda, 0x46, 0x35, 0xe4, 0xee, 0x15, 0x46, 0x37, 0x2c, 0xfd, 0x24, 0xba, 0xd3, 0xb3,
	0x92, 0x17, 0x4c, 0x61, 0xe2, 0x1e, 0x2c, 0x18, 0x1d, 0x9c, 0x37, 0xcd, 0x79, 0x89, 0x89, 0x1e,
	0xcf, 0xea, 0xba, 0x51, 0x4c, 0xf1, 0xa6, 0x96, 0xab, 0xee, 0xe1, 0xaa, 0x6b, 0xaa, 0x45, 0xf7,
	0x21, 0x51, 0xbc, 0x42, 0xa9, 0x58, 0x25, 0xac, 0x21, 0x7e, 0x06, 0xbb, 0xaf, 0xd8, 0xa7, 0x05,
	0xce, 0x9d, 0x4e, 0x28, 0x04, 0xba, 0x08, 0xbd, 0xb1, 0x77, 0x74, 0x6b, 0x1a, 0x51, 0x3b, 0x81,
	0xba, 0x09, 0xf4, 0x8f, 0x33, 0x37, 0xbe, 0xf8, 0xd2, 0x83, 0x20, 0x53, 0x58, 0x91, 0x5d, 0xf0,
	0xb3, 0xd4, 0x60, 0x41, 0xee, 0x67, 0x29, 0x09, 0x61, 0xf4, 0xfa, 0x63, 0x8d, 0x6d, 0x96, 0x86,
	0xbe, 0x11, 0x5d, 0x49, 0x0e, 0x60, 0xe7, 0x8d, 0xdd, 0x31, 0x4b, 0xc3, 0x9b, 0xa6, 0x77, 0x25,
	0x90, 0x3d, 0x18, 0xcc, 0xb9, 0x2a, 0x31, 0x0c, 0xc6, 0xde, 0xd1, 0x4e, 0x6e, 0x0b, 0xf2, 0x10,
	0x46, 0x2f, 0x5a, 0x64, 0x0a, 0x8b, 0x70, 0xb0, 0xf5, 0x66, 0xce, 0x4a, 0x5e, 0xc2, 0xe8, 0x9d,
	0x28, 0x0c, 0x35, 0x34, 0x14, 0xa5, 0xff, 0x0f, 0x9a, 0xfe, 0x9d, 0x46, 0xee, 0xf0, 0xf8, 0x31,
	0xec, 0xa7, 0x28, 0x97, 0x2d, 0x5f, 0xa0, 0xde, 0xf6, 0x74, 0x92, 0xe3, 0x45, 0x87, 0x52, 0x91,
	0x43, 0x18, 0x6a, 0xc1, 0xad, 0x3e, 0x1b, 0xfd, 0x9a, 0x05, 0x53, 0x7f, 0x7c, 0x23, 0x5f, 0xc9,
	0xf1, 0x1c, 0x6e, 0xaf, 0x93, 0x52, 0x34, 0xb5, 0x44, 0xf2, 0x04, 0x06, 0x3d, 0x2b, 0x3b, 0x97,
	0xf5, 0xbd, 0x6d, 0x77, 0xd3, 0x78, 0x6e, 0x91, 0xe9, 0x0f, 0x0f, 0xf6, 0x5d, 0x66, 0x0a, 0xab,
	0xe7, 0x82, 0xbf, 0xc5, 0xb6, 0xe7, 0x4b, 0x24, 0xdf, 0x3d, 0x20, 0xee, 0xc0, 0x39, 0x56, 0xa2,
	0x64, 0x0a, 0x4f, 0x27, 0xe4, 0x64, 0xdb, 0xf4, 0x7f, 0xae, 0x17, 0x3d, 0xba, 0x2e, 0x66, 0x77,
	0x8b, 0xa3, 0xaf, 0x3f, 0x2f, 0xbf, 0xf9, 0x7b, 0x84, 0xe8, 0x8f, 0x5e, 0xfb, 0x65, 0xf2, 0xd9,
	0x06, 0xf2, 0x65, 0x46, 0xdf, 0xdf, 0xdf, 0xfc, 0x4b, 0x8e, 0xb5, 0xe9, 0x98, 0x09, 0xfe, 0x74,
	0xfd, 0x94, 0xc5, 0xd0, 0xbc, 0xe2, 0x07, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xac, 0x88,
	0x67, 0x5c, 0x03, 0x00, 0x00,
}
