// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: passsquale/product_item_api/v1/product_item_api.proto

package product_item_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductItemApiService_DescribeTemplateV1_FullMethodName = "/passsquale.product_item_api.v1.ProductItemApiService/DescribeTemplateV1"
)

// ProductItemApiServiceClient is the client API for ProductItemApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductItemApiServiceClient interface {
	// DescribeItemV1 - Describe a template
	DescribeTemplateV1(ctx context.Context, in *DescribeItemV1Request, opts ...grpc.CallOption) (*DescribeItemV1Response, error)
}

type productItemApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductItemApiServiceClient(cc grpc.ClientConnInterface) ProductItemApiServiceClient {
	return &productItemApiServiceClient{cc}
}

func (c *productItemApiServiceClient) DescribeTemplateV1(ctx context.Context, in *DescribeItemV1Request, opts ...grpc.CallOption) (*DescribeItemV1Response, error) {
	out := new(DescribeItemV1Response)
	err := c.cc.Invoke(ctx, ProductItemApiService_DescribeTemplateV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductItemApiServiceServer is the server API for ProductItemApiService service.
// All implementations must embed UnimplementedProductItemApiServiceServer
// for forward compatibility
type ProductItemApiServiceServer interface {
	// DescribeItemV1 - Describe a template
	DescribeTemplateV1(context.Context, *DescribeItemV1Request) (*DescribeItemV1Response, error)
	mustEmbedUnimplementedProductItemApiServiceServer()
}

// UnimplementedProductItemApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductItemApiServiceServer struct {
}

func (UnimplementedProductItemApiServiceServer) DescribeTemplateV1(context.Context, *DescribeItemV1Request) (*DescribeItemV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTemplateV1 not implemented")
}
func (UnimplementedProductItemApiServiceServer) mustEmbedUnimplementedProductItemApiServiceServer() {}

// UnsafeProductItemApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductItemApiServiceServer will
// result in compilation errors.
type UnsafeProductItemApiServiceServer interface {
	mustEmbedUnimplementedProductItemApiServiceServer()
}

func RegisterProductItemApiServiceServer(s grpc.ServiceRegistrar, srv ProductItemApiServiceServer) {
	s.RegisterService(&ProductItemApiService_ServiceDesc, srv)
}

func _ProductItemApiService_DescribeTemplateV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeItemV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductItemApiServiceServer).DescribeTemplateV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductItemApiService_DescribeTemplateV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductItemApiServiceServer).DescribeTemplateV1(ctx, req.(*DescribeItemV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductItemApiService_ServiceDesc is the grpc.ServiceDesc for ProductItemApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductItemApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "passsquale.product_item_api.v1.ProductItemApiService",
	HandlerType: (*ProductItemApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeTemplateV1",
			Handler:    _ProductItemApiService_DescribeTemplateV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passsquale/product_item_api/v1/product_item_api.proto",
}
